FROM docker.io/library/node:18.16.0-alpine

WORKDIR /faucet-web

COPY ./client/package.json ./
COPY ./client/yarn.lock ./
RUN yarn --frozen-lockfile

COPY ./client .

ARG PUBLIC_FAUCET_URL="https://faucet.sandbox.avail.tools/drip/web"
ARG PUBLIC_CAPTCHA_KEY=""

RUN PUBLIC_FAUCET_URL=$PUBLIC_FAUCET_URL PUBLIC_CAPTCHA_KEY=$PUBLIC_CAPTCHA_KEY yarn build

EXPOSE 3000

ENTRYPOINT [ "node" ]

CMD ["build/index.js"]
